### ISSUE TITLE
About the issue that when one person logs in, others also start with the same login.

### ISSUE THREAD

**Issue by quixote79** [MrBounty/streamlit-google-auth#1]
First, thank you for creating such a great library.
I'm contacting you because I have one problem while using it.

To explain the situation, for example, first I successfully logged in to someone@gmail.com with my chrome browser.

Then, when I access the site with another browser (EDGE for example), it starts with me logged in as someone@gmail.com without any login process.

Even when I access the site from a different computer, unless I log out of someone@gmail.com in the first browser, I still start as someone@gmail.com with no sign-in process.

What am I doing wrong?

**Comment by MrBounty** [comment]
Nothing, I am doing things wrong.

I did an update of this part for my app, I need to update this package. 
Should be soon.

**Comment by MrBounty** [comment]
This should be solve with today update. It solved the issue for me.

**Comment by quixote79** [comment]
hello.
I've been testing with the new fix and the new demo.
I certainly didn't run into the kind of issues I mentioned before, so thanks for the fix.

I have one other question on a related issue.

After logging in, if I press the browser reload button(not Rerun on streamlit), or press F5, it immediately unlogs me out. So I have to log in again.

Is this behavior intended by you?
What I want is to not be logged out unless I specifically hit the logout button.
Is there a way to accomplish this in code?

**Comment by MrBounty** [comment]
I am aware of this issue and it was not intended.  
I will take a look at it soon as I also need this feature.  
So you can assume, unless I can't figure it out, that the feature will arrive soon.
